name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Запускать на создание тега, например, v1.0.0

jobs:
  build:
    runs-on: windows-latest  # Используем Windows для сборки .exe

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2  # Устанавливаем Python
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt
          pip install pyinstaller  # Устанавливаем PyInstaller для сборки .exe

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico SkillViewer.py

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/SkillViewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}